name: Configure Branch Protection
on:
  workflow_dispatch:
    inputs:
      repositoryName:
        description: 'Repository Name'
        required: true
        default: 'branch-protection-test'
      enable-master-protection:
        description: 'Should the master branch protection be applied'
        type: boolean
        required: true
        default: false
      enable-release-protection:
        description: 'Should the master branch protection be applied'
        type: boolean
        required: true
        default: false

jobs:
  Configure-Branch-Protection:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout project sources
        uses: actions/checkout@v5

      - name: Apply master branch ruleset
        if: enable-master-protection
        uses: ./.github/actions/apply-ruleset
        with:
          rulesetName: master-branch-ruleset
          repositoryName: ${{ github.event.inputs.repositoryName }}
          gitPat: ${{ secrets.git_pat }}

      - name: Apply master branch ruleset
        if: enable-release-protection
        uses: ./.github/actions/apply-ruleset
        with:
          rulesetName: release-branch-ruleset
          repositoryName: ${{ github.event.inputs.repositoryName }}
          gitPat: ${{ secrets.git_pat }}
