name: Configure Branch Protection
on:
  workflow_dispatch:
    inputs:
      repositoryName:
        description: 'Repository Name'
        required: true
        default: 'branch-protection-test'
      enable-master-protection:
        description: 'Apply master branch protection'
        type: boolean
        required: true
        default: true
      enable-release-protection:
        description: 'Apply release branch protection'
        type: boolean
        required: true
        default: true

jobs:
  Configure-Branch-Protection:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout project sources
        uses: actions/checkout@v5

      - name: Apply master branch ruleset
        if: ${{ github.event.inputs.enable-master-protection }}
        uses: ./.github/actions/apply-ruleset
        with:
          rulesetName: master-branch-ruleset
          repositoryName: ${{ github.event.inputs.repositoryName }}
          gitPat: ${{ secrets.git_pat }}

      - name: Apply release branch ruleset
        if: ${{ github.event.inputs.enable-release-protection }}
        uses: ./.github/actions/apply-ruleset
        with:
          rulesetName: release-branch-ruleset
          repositoryName: ${{ github.event.inputs.repositoryName }}
          gitPat: ${{ secrets.git_pat }}
